GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "On the meaning of programming",
  "author": "Ismail",
  "url": "google.com",
  "likes": 5
}