GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVrYWkiLCJpZCI6IjY3NGE1MzE5YzJiNTk0YzY4YzcyMWZkZSIsImlhdCI6MTczOTkwNjkxNywiZXhwIjoxNzM5OTEwNTE3fQ.lzK-4DHY900xfVDjNaq3ZXUjin_nXsAaNlzH4oFUtfg

{
  "title": "On the meaning of programming",
  "author": "Ismail",
  "url": "google.com",
  "likes": 5,
  "userId": "674a5319c2b594c68c721fde"
}
###

DELETE http://localhost:3001/api/blogs/67b4df9ef2ed9f55243cf2d3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVrYWkiLCJpZCI6IjY3NGE1MzE5YzJiNTk0YzY4YzcyMWZkZSIsImlhdCI6MTczOTkwNjkxNywiZXhwIjoxNzM5OTEwNTE3fQ.lzK-4DHY900xfVDjNaq3ZXUjin_nXsAaNlzH4oFUtfg

###
PUT http://localhost:3001/api/blogs/672d3af02b79139bb492e248
Content-Type: application/json

{
  "title": "On the meaning of programming",
  "author": "Ismail",
  "url": "google.com",
  "likes": 6
}