POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "VS code rest client is a pretty handy tool",
  "important": true,
  "userId": "673d07ca2349137f72fe5751"
}
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "HTML is easy!",
  "important": true,
  "userId": "673d08112349137f72fe5759"
}
###
GET http://localhost:3001/api/notes
